### ISSUE TITLE
Created bundle.js is too large for wt

### ISSUE THREAD

**Issue by siparsons** [auth0/auth0-alexa-authentication-sample#1]
Having followed the instructions web pack instructions here are my findings:

Initial "npm run build" fails as the code cannot locate webtask-tools
after performing npm install webtask-tools it fails to fund "edge"
after performing npm install edge it now successfully creates the bundle.js file

however

the file is > 4kb and fails with the following:

```
Uncaught error:  Request body size exceeds 122880
Error: Payload Too Large
    at Request.callback (C:\Users\simon\AppData\Roaming\npm\node_modules\wt-cli\node_modules\superagent\lib\node\index.js:675:11)
    at C:\Users\simon\AppData\Roaming\npm\node_modules\wt-cli\node_modules\superagent\lib\node\index.js:883:18
    at IncomingMessage.<anonymous> (C:\Users\simon\AppData\Roaming\npm\node_modules\wt-cli\node_modules\superagent\lib\node\parsers\json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Please report this at: https://github.com/auth0/wt-cli/issues
```

**Comment by michalox** [comment]
@siparsons I have the same issue. Have you found any workaround?

**Comment by thinkingserious** [comment]
Same issue here.

**Comment by oolertt** [comment]
Same issue here.

My bundle.js file is sitting at 4.6MB
